#百度文库 解锁文档阅读权限
#https://raw.githubusercontent.com/deezertidal/QuantumultX-Rewrite/master/rewrite/bdwk.conf
#ddgksf2013

^https:\/\/appwk\.baidu\.com\/naapi\/user\/getinfo url script-response-body https://raw.githubusercontent.com/BigBigBigBigBigDevil/QuantumultX_configuration/main/rewrite/baiduDoc.js



hostname = appwk.baidu.com
