#!name=彩云天气SVIP
#!desc=彩云天气会员解锁
#WeiRen0
#!homepage=https://github.com/WeiRen0

hostname=*.caiyunapp.*,*cyapi*

^http[s]?:\/\/biz\.(caiyunapp|cyapi)\.(com|cn)\/v2\/user.*$ url script-response-body https://raw.githubusercontent.com/BigBigBigBigBigDevil/QuantumultX_configuration/main/rewrite/caiyun.js  

^https:\/\/ad\.caiyunapp\.com\/ url reject
