#89996462
#https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/jxydt.js
#驾校一点通
#必须v10.6.2版本

hostname=vipapi.jxedt.com
^https:\/\/vipapi\.jxedt\.com\/store\/vip\/check url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/jxydt.js
