#Musixmatch
#https://raw.githubusercontent.com/deezertidal/QuantumultX-Rewrite/master/rewrite/musixmatch.conf
#Marol62926

hostname = apic.musixmatch.com
https://apic.musixmatch.com/ws/1.1/config.get url script-response-body https://raw.githubusercontent.com/BigBigBigBigBigDevil/QuantumultX_configuration/main/rewrite/musixmatch.js
